name: Trigger Workflow Dispatch

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:


# FrontEnd Team
# "TaskTypesTitle":"FE-CreatUI,FE-Review,FE-APIIntegration,FE-ReviewStory"
# Backend Team
# "TaskTypesTitle":"[BE][Supplier][Design],[BE] [Supplier][Implementation],[BE] [Supplier][UnitTest],[BE] [Supplier][Review]"
# Testing Team
# "TaskTypesTitle": "Test Analysis,Test Case Preparation,Test Execution,Retesting"
# for Task
      # - name: Create Task Creation Automation Inputs JSON
      #   run: |
      #     echo '{
      #       "ref": "master",
      #       "inputs": {
      #           "AzureToken": "${{ secrets.AZURE_PAT }}",
      #           "Organization": "Azure-Do",
      #           "ProjectName": "Azure-DoDemo",
      #           "ActivateAutoClose": false,
      #           "TaskTypesTitle": "Test Case Preparation,Test Execution,Retesting",
      #           "TaskScope": "All Sprints", 
      #           "TaskUSScope": "All",
      #           "TaskTags": "TestTag"
      #       }
      #     }' > TaskCreationAutomation.json
          
      # - name: Task Creation Automation
      #   run: |
      #     curl --location 'https://api.github.com/repos/MohamedAbdelrehem/AzureTaskAutomate/actions/workflows/Actions_Schedule_check_updates.yml/dispatches' \
      #     --header 'Accept: application/vnd.github+json' \
      #     --header 'Authorization: Bearer ${{ secrets.privateRepoAuth }}' \
      #     --header 'X-GitHub-Api-Version: 2022-11-28' \
      #     --header 'Content-Type: application/json' \
      #     --data @TaskCreationAutomation.json

# ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 
 # for Analysis
      - name: Create Analysis Automation Inputs JSON
        run: |
          echo '{
            "ref": "master",
            "inputs": {
                "AzureToken": "${{ secrets.AZURE_PAT }}",
                "Organization": "Azure-Do",
                "ProjectName": "Azure-DoDemo",
                "POName": "Mohamed",
                "FrontEndIDs": "52c6c14f-82b6-6622-b809-f56e6a1f43e4",
                "BackEndIDs": "52c6c14f-82b6-6622-b809-f56e6a1f43e4",
                "MobileIDs": "52c6c14f-82b6-6622-b809-f56e6a1f43e4",
                "StateReflectKeyword": "Removed"
            }
          }' > AnalysisAutomation.json

      - name: Analysis Automation
        run: |
          curl --location 'https://api.github.com/repos/MohamedAbdelrehem/AzureAnalysisAutomate/actions/workflows/Actions_Schedule_check_updates.yml/dispatches' \
          --header 'Accept: application/vnd.github+json' \
          --header 'Authorization: Bearer ${{ secrets.privateRepoAuth }}' \
          --header 'X-GitHub-Api-Version: 2022-11-28' \
          --header 'Content-Type: application/json' \
          --data @AnalysisAutomation.json
